In [13]:
import unicodedata
import re
import json
import nltk
from nltk.tokenize.toktok import ToktokTokenizer
from nltk.corpus import stopwords
import pandas as pd
import acquire
import nltk
nltk.download('omw-1.4')

[nltk_data] Downloading package omw-1.4 to
[nltk_data]     /Users/evanwilliams/nltk_data...

True

In [ ]:
original = acquire.get_blog_articles()
original

In [ ]:
original = original[0]['content']
original

In [ ]:
# lower case everything 
blog = original.lower()
#print(blog[0:500])
blog

In [ ]:
blog = (unicodedata.normalize('NFKD', blog)
    .encode('ascii', 'ignore')
    .decode('utf-8', 'ignore'))

blog

In [ ]:
# space out any punctuation and break words 
tokenizer = nltk.tokenize.ToktokTokenizer()
blog = tokenizer.tokenize(blog, return_str=True)

In [ ]:
blog

In [ ]:
# remove anything that is not a through z, a number, a single quote, or whitespace
blog = re.sub(r"[^a-z0-9'\s]", '', blog)
print(blog)

clean function

In [2]:
def basic_clean(blog):
    blog = blog.lower()
    blog = (unicodedata.normalize('NFKD', blog)
    .encode('ascii', 'ignore')
    .decode('utf-8', 'ignore'))
    blog = re.sub(r"[^a-z0-9'\s]", '', blog)
    return blog

In [ ]:
basic_clean(blog)

2. tokenize

In [3]:
def tokenize(blog):
    tokenizer = nltk.tokenize.ToktokTokenizer()
    blog = tokenizer.tokenize(blog, return_str=True)
    return blog

In [ ]:
blog = tokenize(blog)

In [ ]:
blog

3. stem function

In [4]:
def stem(blog):
    ps = nltk.porter.PorterStemmer()
    stems = [ps.stem(word) for word in blog.split()]
    article_stemmed = ' '.join(stems)
    return article_stemmed

In [ ]:
stem(blog)

4. lemmatize function

In [5]:
def lemmatize(blog):
    wnl = nltk.stem.WordNetLemmatizer()
    lemmas = [wnl.lemmatize(word) for word in blog.split()]
    article_lemmatized = ' '.join(lemmas)

    return article_lemmatized

In [ ]:
lemmatize(blog)

5. Remove stopwords function

In [6]:
def remove_stopwords(string, extra_words=None, exclude_words=None):
    
    stopword_list = stopwords.words('english')
    
    if exclude_words:
        
        stopword_list = stopword_list + exclude_words
        
    if extra_words:
        
        for word in extra_words:
            
            stopword_list.remove(word)
            
    words = string.split()
    
    filtered_words = [word for word in words if word not in stopword_list]
    
    filtered_string = ' '.join(filtered_words)
    
    return filtered_string

In [7]:
news_json = acquire.get_news_articles()

news_json

[{'title': "India's GDP grows at 13.5% in first quarter of FY23, fastest in a year",
  'content': "India's GDP grew at 13.5% in the first quarter of FY23, achieving its fastest annual expansion in a year, government data showed. However, it is lower than the Reserve Bank of India's (RBI) projection of 16.2% GDP growth in the first quarter of FY23. India's GDP growth in the first quarter of FY22 was 20.1%.",
  'category': 'business'},
 {'title': "Musk seeks to delay Twitter trial to Nov amid whistleblower's claims",
  'content': "Tesla CEO Elon Musk is seeking to delay the trial with Twitter until November, as per court filings. The five-day trial is currently scheduled to start on October 17. The court filings came after Musk's legal team sent a fresh letter to Twitter to include whistleblower Peiter Zatko's claims as another reason to end the $44 billion deal.",
  'category': 'business'},
 {'title': 'Snap to lay off 20% of staff, cancel several projects to cut costs',
  'content': 'Snap said on Wednesday it will lay off 20% of its staff and shut down original shows, in-app games and several other projects as part of a corporate restructuring. As per CEO  Evan Spiegel, Snap\'s current revenue growth rate is "well below" what the company was expecting. The cut will help Snap save an estimated $500 million in costs annually. ',
  'category': 'business'},
 {'title': '2 top executives at Snap quit hours after report about 20% layoffs emerges',
  'content': 'Two senior advertising executives at Snap quit hours after a report emerged stating that the company was planning to cut about 20% of its workforce. Earlier, a report by The Verge, while citing sources, said that Snap is planning to lay off 20% of its more than 6,400 employees after it reported weak Q2 results. ',
  'category': 'business'},
 {'title': 'Viral video shows Amazon parcels thrown out of train at station, Railways clarifies',
  'content': 'A video from Guwahati railway station has gone viral which shows Amazon parcels being thrown on the platform as they are unloaded from a train. After some social media users alleged that Railways\' employees were carelessly unloading the parcels, Northeast Frontier Railway said, "This is an old video from March, 2022...The persons handling parcels are representatives of concerned party."',
  'category': 'business'},
 {'title': 'Dell among firms conducting stay interviews to contain high attrition rates: Report',
  'content': 'To contain the high attrition rates, some companies are now reportedly using stay interviews. In stay interviews, companies speak to the employees about their importance to the organisation while addressing the issues they might be facing prompting them to quit. Dell Technologies and Ericsson are among the companies which have been conducting such interviews with employees. ',
  'category': 'business'},
 {'title': "World's 3rd richest person Adani's wealth surged over 13 times in 2.5 years",
  'content': "Adani Group Chairman Gautam Adani on Tuesday became the world's third richest person with a net worth of $137 billion. While his wealth stood at $10 billion on January 1, 2020, it surged by over $60 billion in 2022 alone and jumped more than thirteen times in over two and half years. Currently, his net worth stands at $143 billion. ",
  'category': 'business'},
 {'title': "Russia's Gazprom halts gas supply to Europe via major pipeline",
  'content': 'Russia stopped gas supplies via a major pipeline to Europe on Wednesday with state energy company Gazprom saying that no gas would flow into Germany between Wednesday and Saturday. This is because of the outage for maintenance on Nord Stream 1. While European governments have accused Russia of using energy supplies as a "weapon of war", Moscow has denied this.\n',
  'category': 'business'},
 {'title': 'Netflix hires 2 top advertising executives from Snapchat-parent Snap Inc',
  'content': "Netflix on Tuesday announced that it has hired two top executives from Snap Inc. The firm's Chief Business Officer Jeremi Gorman has been hired as Netflix's head of worldwide advertising while Snap Inc's VP of advertising sales Peter Naylor has been hired for the same role. The hiring signals Netflix's commitment to building an ad-supported version of its streaming service.",
  'category': 'business'},
 {'title': 'Japan calls for $24 bn investment to boost battery competitiveness',
  'content': "Japan's Ministry of Economy, Trade and Industry said that the country needs an investment worth over $24 billion from the public and private sectors to develop a competitive manufacturing base for batteries used in electric vehicles (EVs). A specialist panel has set a target of securing 30,000 trained workers for battery manufacturing and supply chains by 2030.\n",
  'category': 'business'},
 {'title': 'Infosys divests entire stake in US-based Trifacta for $12 million',
  'content': "Infosys said that it has divested its stake in Trifacta Inc, a data preparation software company, for $12 million. Infosys had invested $4 million in the San Francisco-based company in 2016. It had a minority holding not exceeding 20% of Trifacta's outstanding share capital. Trifacta was founded in 2012 and its investors include Accel, Greylock Partners, Ignition and Cathay Innovation.\n",
  'category': 'business'},
 {'title': 'SoftBank Corporate Officer Rajeev Misra steps down amid record loss',
  'content': "SoftBank Group's Corporate Officer and Executive Vice President Rajeev Misra is stepping down from his roles, the Japanese conglomerate said on Wednesday. This development follows a record loss at the Japanese investment group after a slide in technology stocks. Misra will retain his position as head of SoftBank Investment Advisers, which oversees the first Vision Fund's existing investments.\n",
  'category': 'business'},
 {'title': 'Axis Bank looking to acquire 10% stake in Go Digit: Report',
  'content': 'Axis Bank is looking to acquire a 10% stake for around $9 million in Go Digit Life Insurance, as per a report. Last week, HDFC Bank in a regulatory filing declared that it was planning to buy a 9.94% stake in Go Digit Life for $9 million. Go Digit Insurance recently filed papers to raise $440 million via an IPO. ',
  'category': 'business'},
 {'title': 'Dennis Woodside appointed as President of Freshworks',
  'content': "Nasdaq-listed software-as-a-service (SaaS) company Freshworks has appointed Dennis Woodside as the company's President, effective from September 1. Woodside will join the company's board of directors and will report to Freshworks CEO and Founder Girish Mathrubootham. Previously, he was President of Impossible Foods, and also worked at Dropbox and Google. At Freshworks, he will lead global business operations.",
  'category': 'business'},
 {'title': "Tata Motors completes buying of Marcopolo's stake for ₹99.96 crore",
  'content': "Tata Motors has completed the acquisition of its partner Marcopolo's stake in their joint venture Tata Marcopolo Motors Limited (TMML) for ₹99.96 crore. The 51:49 joint venture between the two was formed in 2006. Tata Motors and Marcopolo had signed a deal under which the former agreed to purchase 49% shareholding of Marcopolo in the joint venture in December 2020.\n",
  'category': 'business'},
 {'title': 'States, UTs to get chana at ₹8/kg discount for welfare schemes',
  'content': 'The Union Cabinet has approved the disposal of 15 lakh tonne of chana to states and Union Territories at a discount of ₹8/kg for utilisation in various welfare schemes. These will be offered on a "first come, first served" basis and can be utilised in Mid Day Meal Scheme, Public Distribution System and Integrated Child Development Services, among others.',
  'category': 'business'},
 {'title': 'IMF to make formal announcement on SL bailout package on Thurs: Report',
  'content': "International Monetary Fund (IMF) is likely to conclude talks with the Sri Lankan government and make a formal announcement on Thursday on the bailout package and staff-level agreement for the cash-strapped country, according to reports. The ongoing talks are regarding a $5 billion bailout package for Sri Lanka. This is IMF delegation's second visit to Sri Lanka in three months.",
  'category': 'business'},
 {'title': 'Pak at challenging economic juncture: IMF while approving bailout',
  'content': 'Pakistan is at a "challenging economic juncture", the International Monetary Fund (IMF) said while approving a $1.17 billion bailout plan amid widespread destruction due to floods. IMF\'s Executive Board completed the reviews of a loan facility for Pakistan on Monday. It will put the cash-starved country\'s economy back on track averting an imminent default amid persisting political uncertainty.\n',
  'category': 'business'},
 {'title': 'Tata Steel to invest in hydrogen-based steel production in Netherlands',
  'content': 'Tata Steel has said that it will invest more than €65 million for hydrogen-based steel manufacturing in the Netherlands. The company has signed pacts with three firms - McDermott, Danieli and Hatch for further technical preparations. McDermott will manage construction input, Danieli will oversee engineering design and Hatch will help improve the final steel quality.',
  'category': 'business'},
 {'title': 'FPIs turn net buyers of Indian shares in a month 1st time since Sept 2021',
  'content': "In August 2022, the first month of net inflows for Dalal Street since September 2021, foreign portfolio investors (FPIs) emerged as net buyers of Indian equities with net purchases at ₹22,025.8 crore for the month, provisional exchange data showed. Net sales by domestic institutional investors (DIIs) stood at ₹7,068.9 crore. This was first month of DIIs' outflows in 16 months.",
  'category': 'business'},
 {'title': 'Air India retains Captain RS Sandhu as Chief of Operations',
  'content': "Tata-owned Air India announced on Tuesday that Captain RS Sandhu will continue to lead as its Chief of Operations till further notice. In July 2020, the Appointments Committee of the Cabinet cleared his appointment for the role. This makes Sandhu one of the few top management people from Air India's government-owned days to be retained after the Tatas took over.",
  'category': 'business'},
 {'title': 'NSDL likely to shortlist 7 investment banks for 2023 IPO: Reports',
  'content': "IDBI Bank and the NSE-backed National Securities Depository Limited (NSDL) is likely to shortlist seven investment banks as advisors in its preparation to launch an initial public offer next year, according to reports. If the listing is successful, NSDL will become the second depository services firm to be listed on Indian bourses after Central Depository Services Limited's debut in 2017.\n",
  'category': 'business'},
 {'title': 'NPCI receives RBI nod to acquire 10% stake in ONDC',
  'content': 'The National Payments Corporation of India (NPCI) has received clearance from Reserve Bank of India (RBI) and Union Ministry of Finance to acquire a 10% stake in Open Network for Digital Commerce (ONDC). Reportedly, Bank of India is also looking to acquire 5-7% stake in the company. ONDC currently has 17 stakeholders, and is aiming to have 20. ',
  'category': 'business'},
 {'title': 'Reliance Industries acquires soft drink brand Campa: Report',
  'content': 'Reliance Industries has acquired soft drink brand Campa from Pure Drinks Group to add to its FMCG portfolio, as per reports. The deal is estimated to be ₹22 crore and Reliance is looking to re-launch Campa nationally by Diwali in three flavours. This will include its original Campa Cola, lemon and orange variants.',
  'category': 'business'},
 {'title': "India's B2B general trade to reach $1.2 trillion by 2030: Redseer",
  'content': "According to a report by Redseer Strategy Consultants, the general business-to-business (B2B) trade in India will reach $1.2 trillion by 2030, with the driving factor being B2B e-commerce. The unorganised general trade channel that drives India's retail market will double from $0.7 trillion to $1.4 trillion. The B2B e-commerce market will reach $90-100 billion in gross merchandise value. ",
  'category': 'business'},
 {'title': 'India beat Hong Kong to reach Asia Cup Super 4 as Suryakumar breaks multiple records',
  'content': 'India beat Hong Kong by 40 runs to qualify for Super 4 stage of Asia Cup 2022. Suryakumar Yadav slammed 68*(26), the highest score by a batter in the ongoing tournament. He also recorded most sixes by an Indian (six) in a T20 Asia Cup match and most runs by an Indian (26) in 20th over of a T20I match.',
  'category': 'sports'},
 {'title': 'Suryakumar Yadav smashes most sixes ever by an Indian in a T20 Asia Cup match',
  'content': "Suryakumar Yadav on Wednesday broke the record for smashing the most number of sixes by a Team India batter in a men's T20 Asia Cup match. Suryakumar slammed six sixes against Hong Kong on Wednesday. No other Indian batter has slammed more than three sixes in a men's T20 Asia Cup match. Suryakumar scored 68*(26) against Hong Kong.",
  'category': 'sports'},
 {'title': 'Hardik Pandya achieves his highest-ever spot in rankings for T20I all-rounders',
  'content': 'Following his match-winning performance against Pakistan, Team India all-rounder Hardik Pandya jumped eight places in the latest rankings for T20I all-rounders to a career-best fifth position. Pandya took three wickets and scored an unbeaten 33 off 17 deliveries against Pakistan. Pandya is ranked 76th and 79th in T20I rankings for batters and bowlers, respectively.',
  'category': 'sports'},
 {'title': 'Indian fan receives death threats for wearing Pakistan jersey during India-Pakistan match',
  'content': 'Indian fan, who was seen wearing a Pakistan jersey during the Indian-Pakistan Asia Cup 2022 match in Dubai on Sunday, has received death threats, with people terming him a "traitor". The man, who hails from Uttar Pradesh, stated that he wore Pakistan jersey to tease Pakistani fans. He added that when he reached the stadium, Indian jerseys were sold out.',
  'category': 'sports'},
 {'title': 'Man steals 1-day-old infant from UP hospital by posing as hospital staff, video surfaces',
  'content': "A CCTV footage has surfaced online showing a man stealing a one-day-old infant from a hospital in Uttar Pradesh's Meerut. A complaint has been filed by the parents of the infant, in which they mentioned that the man posed as a hospital staff member for stealing the baby. The police has formed a team to nab the accused.",
  'category': 'sports'},
 {'title': 'India announce their playing XI for match against Hong Kong, Hardik Pandya rested',
  'content': 'Hong Kong captain Nizakat Khan won the toss and elected to bowl first against India in their Asia Cup 2022 match on Wednesday. India have made one change to their playing XI, with Rishabh Pant replacing Hardik Pandya. India captain Rohit Sharma said at the toss that they are resting Hardik, who was named Player of the Match against Pakistan.',
  'category': 'sports'},
 {'title': 'Rohit Sharma becomes first cricketer to reach 3,500 runs in T20I cricket',
  'content': "Team India captain Rohit Sharma has become the first cricketer to score 3,500 runs in T20I cricket. The 35-year-old reached the milestone during his 13-ball 21-run innings against Hong Kong in Asia Cup 2022. It was Rohit's 126th innings in T20Is. Rohit also holds the record for most hundreds in T20I cricket with four tons.",
  'category': 'sports'},
 {'title': 'Tennis player Sara responds to criticism over father, coach patting her backside after win',
  'content': 'Czechia\'s 16-year-old tennis player Sara Bejlek responded to criticism over her father and coach patting her backside after her win in US Open. "It may...seem inconvenient & uncomfortable to some...but we\'ve already discussed it...It won\'t happen again," Sara said. She added, "If something similar happened in...Czechia...no one would deal with it...But since we\'re in US...everyone comments on it."',
  'category': 'sports'},
 {'title': 'Virat Kohli bowls in T20I cricket after 6 years, concedes 6 runs in an over',
  'content': 'Former Team India captain Virat Kohli on Wednesday bowled an over against Hong Kong in their Asia Cup 2022 match. It is the first time since 2016 that Kohli bowled in a T20I match. He gave away six runs in his over. Kohli has bowled 25.2 overs in T20I cricket, taking four wickets for 204 runs.',
  'category': 'sports'},
 {'title': "I have no idea, this question is out of my book: Jadeja on why Pant didn't play vs Pak",
  'content': 'During a press conference ahead of India-Hong Kong Asia Cup 2022 match, a journalist asked Ravindra Jadeja why Rishabh Pant wasn\'t included in India\'s playing XI for the match against Pakistan. Jadeja responded, "I have no idea about this. This question is out of my book." India will face Hong Kong tonight.',
  'category': 'sports'},
 {'title': 'India, Pakistan players fined 40% of match fee each for slow over-rate offence',
  'content': "India and Pakistan players have been fined 40% of their match fee each for maintaining a slow over-rate in their Asia Cup 2022 match on Sunday. Match referee Jeff Crowe imposed the sanctions after Rohit Sharma and Babar Azam's sides were ruled to be two overs short of their respective targets after time allowances were taken into consideration.",
  'category': 'sports'},
 {'title': 'Virat Kohli bows down to Suryakumar Yadav, asks crowd to cheer for him; video goes viral',
  'content': 'A video went  viral showing Virat Kohli bowing down to Suryakumar Yadav after his knock of 68*(26) against Hong Kong in Asia Cup on Wednesday. Kohli was also seen asking the crowd to cheer for Suryakumar while walking back to the dressing room. Kohli and Suryakumar shared an unbeaten partnership of 98 runs as India registered a total of 192/2.',
  'category': 'sports'},
 {'title': "I was surprised by Pant's exclusion from playing XI vs Pak: Parthiv",
  'content': 'Ex-India cricketer Parthiv Patel has said that he was surprised by Rishabh Pant\'s exclusion from India\'s playing XI against Pakistan in the Asia Cup. "Everyone is debating over who should play, Rishabh Pant or Dinesh Karthik. But that\'s a wrong comparison...I feel Kohli should open in place of KL Rahul and Pant should bat in the middle order," added Parthiv.',
  'category': 'sports'},
 {'title': "No point in Hardik playing against HK if he isn't going to bowl: Parthiv",
  'content': 'Ex-Team India wicketkeeper-batter Parthiv Patel said there is "no point" in Team India all-rounder Hardik Pandya playing against Hong Kong if he is not going to bowl. "I don\'t see Hardik bowling against Hong Kong...If he isn\'t playing, then Deepak Hooda could come in," added Parthiv. Hardik picked three wickets while conceding 25 runs in India\'s win against Pakistan.',
  'category': 'sports'},
 {'title': "You're doing grave injustice to him: Aakash on Karthik batting at no. 7",
  'content': 'Commentator Aakash Chopra has said if Team India needs a left-hander at the number four position, then Rishabh Pant should be included in the playing XI. "Because, at number seven, you are doing a grave injustice to Dinesh Karthik also," stated Aakash. India had promoted left-handed all-rounder Ravindra Jadeja to the number four position against Pakistan. ',
  'category': 'sports'},
 {'title': "India faced a 'lot of difficulty' when they last played Hong Kong: Jaffer",
  'content': 'Ex-Team India opener Wasim Jaffer said Team India faced a "lot of" difficulty when they last played against Hong Kong in the Asia Cup in 2018. "They had a 174-175 run opening partnership...It was a very close match...India won\'t be complacent at all," added Jaffer. Hong Kong captain Nizakat Khan earlier stated "anything can happen" when the teams face off.',
  'category': 'sports'},
 {'title': "I don't think one or two failures will make them drop Rahul: Jaffer",

In [8]:
news_df = pd.read_json('news_articles.json')

news_df.head()

,title,content,category
0,India's GDP grows at 13.5% in first quarter of...,India's GDP grew at 13.5% in the first quarter...,business
1,Musk seeks to delay Twitter trial to Nov amid ...,Tesla CEO Elon Musk is seeking to delay the tr...,business
2,"Snap to lay off 20% of staff, cancel several p...",Snap said on Wednesday it will lay off 20% of ...,business
3,2 top executives at Snap quit hours after repo...,Two senior advertising executives at Snap quit...,business
4,Viral video shows Amazon parcels thrown out of...,A video from Guwahati railway station has gone...,business

In [9]:
#Read in the codeup blog posts as well
codeup_df = pd.read_json('blog_posts.json')

codeup_df.head()

,title,date_published,content
0,Codeup’s New Dallas Campus,"Jul 25, 2022",\nCodeup’s Dallas campus has a new location! F...
1,What Jobs Can You Get After a Coding Bootcamp?...,"Jul 7, 2022",\nIf you are interested in embarking on a care...
2,Mental Health First Aid Training,"May 31, 2022","\nAs a student of Codeup, going through a mass..."
3,Inclusion at Codeup During Pride Month (and Al...,"Jun 1, 2022",\nHappy Pride Month! Pride Month is a dedicate...
4,Is Our Cloud Administration Program Right for ...,"Jun 8, 2022",\nChanging careers can be scary. The first thi...

In [10]:
# clean df
news_df['clean'] = news_df['content'].apply(basic_clean).apply(tokenize).apply(remove_stopwords)

news_df.head()

,title,content,category,clean
0,India's GDP grows at 13.5% in first quarter of...,India's GDP grew at 13.5% in the first quarter...,business,india ' gdp grew 135 first quarter fy23 achiev...
1,Musk seeks to delay Twitter trial to Nov amid ...,Tesla CEO Elon Musk is seeking to delay the tr...,business,tesla ceo elon musk seeking delay trial twitte...
2,"Snap to lay off 20% of staff, cancel several p...",Snap said on Wednesday it will lay off 20% of ...,business,snap said wednesday lay 20 staff shut original...
3,2 top executives at Snap quit hours after repo...,Two senior advertising executives at Snap quit...,business,two senior advertising executives snap quit ho...
4,Viral video shows Amazon parcels thrown out of...,A video from Guwahati railway station has gone...,business,video guwahati railway station gone viral show...

In [11]:
# clean news df
news_df['stemmed'] = news_df['clean'].apply(stem)

news_df.head()

,title,content,category,clean,stemmed
0,India's GDP grows at 13.5% in first quarter of...,India's GDP grew at 13.5% in the first quarter...,business,india ' gdp grew 135 first quarter fy23 achiev...,india ' gdp grew 135 first quarter fy23 achiev...
1,Musk seeks to delay Twitter trial to Nov amid ...,Tesla CEO Elon Musk is seeking to delay the tr...,business,tesla ceo elon musk seeking delay trial twitte...,tesla ceo elon musk seek delay trial twitter n...
2,"Snap to lay off 20% of staff, cancel several p...",Snap said on Wednesday it will lay off 20% of ...,business,snap said wednesday lay 20 staff shut original...,snap said wednesday lay 20 staff shut origin s...
3,2 top executives at Snap quit hours after repo...,Two senior advertising executives at Snap quit...,business,two senior advertising executives snap quit ho...,two senior advertis execut snap quit hour repo...
4,Viral video shows Amazon parcels thrown out of...,A video from Guwahati railway station has gone...,business,video guwahati railway station gone viral show...,video guwahati railway station gone viral show...

In [14]:
news_df['lemmatized'] = news_df['clean'].apply(lemmatize)

news_df.head()

,title,content,category,clean,stemmed,lemmatized
0,India's GDP grows at 13.5% in first quarter of...,India's GDP grew at 13.5% in the first quarter...,business,india ' gdp grew 135 first quarter fy23 achiev...,india ' gdp grew 135 first quarter fy23 achiev...,india ' gdp grew 135 first quarter fy23 achiev...
1,Musk seeks to delay Twitter trial to Nov amid ...,Tesla CEO Elon Musk is seeking to delay the tr...,business,tesla ceo elon musk seeking delay trial twitte...,tesla ceo elon musk seek delay trial twitter n...,tesla ceo elon musk seeking delay trial twitte...
2,"Snap to lay off 20% of staff, cancel several p...",Snap said on Wednesday it will lay off 20% of ...,business,snap said wednesday lay 20 staff shut original...,snap said wednesday lay 20 staff shut origin s...,snap said wednesday lay 20 staff shut original...
3,2 top executives at Snap quit hours after repo...,Two senior advertising executives at Snap quit...,business,two senior advertising executives snap quit ho...,two senior advertis execut snap quit hour repo...,two senior advertising executive snap quit hou...
4,Viral video shows Amazon parcels thrown out of...,A video from Guwahati railway station has gone...,business,video guwahati railway station gone viral show...,video guwahati railway station gone viral show...,video guwahati railway station gone viral show...

In [15]:
#Repeat the cleaning process on the codeup blog articles
codeup_df['clean'] = codeup_df['content'].apply(basic_clean).apply(tokenize).apply(remove_stopwords)

codeup_df.head()

,title,date_published,content,clean
0,Codeup’s New Dallas Campus,"Jul 25, 2022",\nCodeup’s Dallas campus has a new location! F...,codeups dallas campus new location two years c...
1,What Jobs Can You Get After a Coding Bootcamp?...,"Jul 7, 2022",\nIf you are interested in embarking on a care...,interested embarking career tech youre probabl...
2,Mental Health First Aid Training,"May 31, 2022","\nAs a student of Codeup, going through a mass...",student codeup going massive career transition...
3,Inclusion at Codeup During Pride Month (and Al...,"Jun 1, 2022",\nHappy Pride Month! Pride Month is a dedicate...,happy pride month pride month dedicated time c...
4,Is Our Cloud Administration Program Right for ...,"Jun 8, 2022",\nChanging careers can be scary. The first thi...,changing careers scary first thing may asking ...

In [16]:
codeup_df['stemmed'] = codeup_df['clean'].apply(stem)
codeup_df['lemmatized'] = codeup_df['clean'].apply(lemmatize)
codeup_df.head()

,title,date_published,content,clean,stemmed,lemmatized
0,Codeup’s New Dallas Campus,"Jul 25, 2022",\nCodeup’s Dallas campus has a new location! F...,codeups dallas campus new location two years c...,codeup dalla campu new locat two year codeup o...,codeups dallas campus new location two year co...
1,What Jobs Can You Get After a Coding Bootcamp?...,"Jul 7, 2022",\nIf you are interested in embarking on a care...,interested embarking career tech youre probabl...,interest embark career tech your probabl wonde...,interested embarking career tech youre probabl...
2,Mental Health First Aid Training,"May 31, 2022","\nAs a student of Codeup, going through a mass...",student codeup going massive career transition...,student codeup go massiv career transit mental...,student codeup going massive career transition...
3,Inclusion at Codeup During Pride Month (and Al...,"Jun 1, 2022",\nHappy Pride Month! Pride Month is a dedicate...,happy pride month pride month dedicated time c...,happi pride month pride month dedic time celeb...,happy pride month pride month dedicated time c...
4,Is Our Cloud Administration Program Right for ...,"Jun 8, 2022",\nChanging careers can be scary. The first thi...,changing careers scary first thing may asking ...,chang career scari first thing may ask begin l...,changing career scary first thing may asking b...

In [17]:
news_df.to_csv('clean_articles.csv', index=False)
codeup_df.to_csv('clean_blog_posts.csv', index=False)